os: linux
language: python
python:
  - "2.7"
  - "3.6"
env:
  PYTHON: python
  PIP: pip
matrix:
  include:
    - os: osx
      language: generic
      env:
        PYTHON: python2
        PIP: pip2
    - os: osx
      language: generic
      env:
        PYTHON: python3
        PIP: pip3
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    if [ "$PYTHON" == "python2" ]; then
      brew install python@2 || brew link --overwrite python@2
    elif [ "$PYTHON" == "python3" ]; then
      brew upgrade python
    fi
  fi
install: $PIP install tox-travis
script: tox
