sudo: false
language: python
python:
    - "2.7"
    - "3.6"
matrix:
  include:
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python
install: pip install tox-travis
script: tox
