language: python
env:
  PIP: pip
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.6"
    - os: osx
      language: generic
      python: "2.7"
      env:
        PIP: pip2
        TOXENV: py27
    - os: osx
      language: generic
      python: "3.6"
      env:
        PIP: pip3
        TOXENV: py36
before_install: |
  mkdir -p $HOME/bin
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget -O $HOME/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio
  elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
    wget -O $HOME/bin/minio https://dl.minio.io/server/minio/release/darwin-amd64/minio
    if [ "$TOXENV" == "py27" ]; then
      brew install python@2 || brew link --overwrite python@2
    elif [ "$TOXENV" == "py36" ]; then
      brew upgrade python
    fi
  fi
  chmod +x $HOME/bin/minio
  export PATH=$HOME/bin:$PATH
install: $PIP install tox-travis
script: tox
